### ISSUE TITLE
Optimized build settings

### ISSUE THREAD

**Issue by joaoeudes7** [MaxGraey/assemblyscript-compiler-bench#1]
Hi, I noticed that in package.json scripts (execution scripts) not all build optimizations are active, neither in Rust nor in AssemblyScript

**Comment by MaxGraey** [comment]
yes, that's because V's compile time also measured without any optimizations) So it was done for that everyone would be on the same conditions

**Comment by MaxGraey** [comment]
You shouldn't take this test too seriously either, it's just an attempt to show that V compilation speed is nothing special, especially on such naive example)

**Comment by joaoeudes7** [comment]
Ahh yes, now I got it right, thanks!
